### ISSUE TITLE
源代码导入kraken，报错 Failed to load dynamic library (dlopen(kraken_bridge.framework/kraken_bridge, 1): image not found)

### ISSUE THREAD

**Issue by WK726** [openkraken/website#177]
由于公司项目的原因，只能以源码形式引入，不能通过pubspec.yaml引入

具体引用方式 kraken - 0.7.3 ：

flutter:在flutter中以源码的形式引入kraken的lib 代码部分
ios:引入demo中的kraken.h .m 以及krakenPlugin.h .m
AppDelegate：注册 [KrakenPlugin registerWithRegistrar:[self registrarForPlugin:@"KrakenPlugin"]];

[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen(kraken_bridge.framework/kraken_bridge, 1): image not found)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)

上边是ios报的错误

**Comment by WK726** [comment]
没有添加kraken_bridge.framework的原因，添加上就可以了
