### ISSUE TITLE
windows环境下运行npm run build:bridge:xxx报错

### ISSUE THREAD

**Issue by yifei8** [openkraken/website#214]
$ npm run build:bridge:android

> @ build:bridge:android D:\kraken
> node scripts/build_android_so

CMake Warning:
  Ignoring extra path from command line:

   "\"

CMake Error: The source directory "/" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
D:\kraken\node_modules\async-done\index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 2,
  name: 'build-android-kraken-lib',
  branch: false,
  error: Error: Command failed: cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=D:\Android\Sdk\ndk\21.4.7075529\build\cmake\android.toolchain.cmake     -DANDROID_NDK=D:/Android/Sdk/ndk/21.4.7075529     -DIS_ANDROID=TRUE     -DANDROID_ABI="arm64-v8a"     \
           -DANDROID_PLATFORM="android-18"     -DANDROID_STL=c++_shared     -G "Ninja"     -B D:\kraken\bridge/cmake-build-android-arm64-v8a -S D:\kraken\bridge
      at checkExecSyncError (child_process.js:635:11)
      at execSync (child_process.js:671:15)
      at D:\kraken\scripts\tasks.js:669:5
      at Array.forEach (<anonymous>)
      at D:\kraken\scripts\tasks.js:665:9
      at build-android-kraken-lib (D:\kraken\node_modules\undertaker\lib\set-task.js:13:15)
      at bound (domain.js:427:14)
      at runBound (domain.js:440:12)
      at asyncRunner (D:\kraken\node_modules\async-done\index.js:55:18)
      at processTicksAndRejections (internal/process/task_queues.js:79:11) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 17812,
    stdout: null,
    stderr: null,
    domainThrown: true
  },
  duration: [ 0, 43482416 ],
  time: 1650361240413
})
    at Gulp.emit (events.js:303:17)
    at Gulp.EventEmitter.emit (domain.js:483:12)
    at Object.error (D:\kraken\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (D:\kraken\node_modules\now-and-later\lib\mapSeries.js:47:14)
    at f (D:\kraken\node_modules\once\once.js:25:25)
    at f (D:\kraken\node_modules\once\once.js:25:25)
    at tryCatch (D:\kraken\node_modules\async-done\index.js:24:15)
    at done (D:\kraken\node_modules\async-done\index.js:40:12)
    at Domain.onError (D:\kraken\node_modules\async-done\index.js:51:5)
    at Object.onceWrapper (events.js:421:26) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    uid: 2,
    name: 'build-android-kraken-lib',
    branch: false,
    error: Error: Command failed: cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=D:\Android\Sdk\ndk\21.4.7075529\build\cmake\android.toolchain.cmake     -DANDROID_NDK=D:/Android/Sdk/ndk/21.4.7075529     -DIS_ANDROID=TRUE     -DANDROID_ABI="arm64-v8a"     \
             -DANDROID_PLATFORM="android-18"     -DANDROID_STL=c++_shared     -G "Ninja"     -B D:\kraken\bridge/cmake-build-android-arm64-v8a -S D:\kraken\bridge
        at checkExecSyncError (child_process.js:635:11)
        at execSync (child_process.js:671:15)
        at D:\kraken\scripts\tasks.js:669:5
        at Array.forEach (<anonymous>)
        at D:\kraken\scripts\tasks.js:665:9
        at build-android-kraken-lib (D:\kraken\node_modules\undertaker\lib\set-task.js:13:15)
        at bound (domain.js:427:14)
        at runBound (domain.js:440:12)
        at asyncRunner (D:\kraken\node_modules\async-done\index.js:55:18)
        at processTicksAndRejections (internal/process/task_queues.js:79:11) {
      status: 1,
      signal: null,
      output: [ null, null, null ],
      pid: 17812,
      stdout: null,
      stderr: null,
      domainThrown: true
    },
    duration: [ 0, 43482416 ],
    time: 1650361240413
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:bridge:android: `node scripts/build_android_so`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:bridge:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\11095194\AppData\Roaming\npm-cache\_logs\2022-04-19T09_40_40_431Z-debug.log

**Comment by yifei8** [comment]
想将kraken跑起来，按咱们的文档来跑不起来，谁给解决一下。https://openkraken.com/guide/contribute/environment

**Comment by yifei8** [comment]
@yuanyan

**Comment by yifei8** [comment]
目前发现是在windows10下有问题
